### ISSUE TITLE
환경변수 대해 질문드려요!

### ISSUE THREAD

**Issue by kokbee** [studio2l/run#1]
안녕하세요. 용빈TD님! di 파이프라인팀 김민수라고 합니다.

사용중에 궁금한점이 있어서 이슈 남깁니다!

환경변수를 배열형태로 부를려고 하면 어떻게 해야하나요?
bash 형태의 환경세팅이라 'PATH=()'의 형태로 bash script 배열을 작성을 햇는데 
fatal error가 나서 문의 드립니다~!

**Comment by kybin** [comment]
아 콜론을 이용해서 각 값들을 구분해주어야 합니다.

VAR=/a/b:/a/c 처럼하면 /a/b와 /a/c 둘 다가 되는데 이는 제가 처리하는게 아니라 OS들이 알아서 처리해주는거에요.

run을 테스트 해주셔서 감사합니다 ㅋㅋ

**Comment by kybin** [comment]
fatal error가 나셨다고 했는데 혹시 어떤 메시지였는지 알려주시면 디버깅에 도움이 될 것 같습니다.

**Comment by kokbee** [comment]
콜론으로 하니까 됬습니다 ㅎㅎ 감사합니다~
fatal error 가 난 부분은 제가 maya로 테스트중이라 shelf creating error 였어요~

**Comment by kokbee** [comment]
그리고 추가로 문자열이 너무길어서 줄바꿈을 하고 싶을때는 어떻게 하나요?

**Comment by kybin** [comment]
VAR=/a/b
VAR=$VAR:/a/c

처럼 할수 있습니다.

**Comment by kokbee** [comment]
잘됩니다 ~ 감사합니다!

**Comment by kybin** [comment]
네, 궁금하신것 있으시면 언제든 물어보세요. 이 이슈는 닫겠습니다!
