### ISSUE TITLE
OS 폴더 위치나, 파일을 불러오는 곳이 서로 다를때

### ISSUE THREAD

**Issue by kokbee** [studio2l/run#3]
용빈 TD님 maya로 리눅스는 테스트를 하고 잘 되었는데, 윈도우의 경우 폴더경로 및 파일의 경우 가 다를 땐 어떻게 하나요? 그리고 특정 아규 먼트를 입력하면 다른 env를 실행하고 싶으면 어떻게하나요?

**Comment by kybin** [comment]
OS 별로 다른 경로를 이용하려면 환경변수를 이용하여야 합니다.
모든 컴퓨터에 루트를 가리키는 환경변수가 있어야 합니다. 투엘에서는 SITE_ROOT라는 환경변수를 모든 컴퓨터에 설정합니다.

또는 별개의 env 파일을 만드는 것도 방법입니다.

**Comment by kybin** [comment]
> 그리고 특정 아규 먼트를 입력하면 다른 env를 실행하고 싶으면 어떻게하나요?

그 기능은 run에는 존재하지 않습니다. 사용 예를 들어주시면 run을 통해 할 수 있는 방법을 생각해보고 알려드리겠습니다.

**Comment by kokbee** [comment]
그렇군요 ㅜㅜ.. 감사합니다!

**Comment by kybin** [comment]
언제든 또 물어봐 주세요~
