### ISSUE TITLE
윈도우에서 공유폴더를 환경변수로 잡을때 문제입니다.

### ISSUE THREAD

**Issue by 78963l** [studio2l/run#4]
윈도우에서 드라이브 맵핑을 안하고 공유폴더를 환경변수로 잡으려 할 때
경로의 맨앞에 // 가들어가는데 env에서 // 두개로 잡으면 환경변수로 잡지만
리눅스에서는 // 두개를 잡지 못하는 문제가 있습니다.
이 문제는 어떻게 해야될까요?

**Comment by 78963l** [comment]
main=/example일 때 윈도우에서
C:/example로의 전환이 아니라 //example로 전환돼야합니다.

**Comment by kybin** [comment]
집에서 확인해보겠습니다. 두번째 덧글이 잘 이해되지 않는데 조금만 더 자세히 말씀해주시겠어요?

**Comment by kybin** [comment]
혹시 리눅스와 윈도우즈 환경변수를 한번에 잡으시려는 거라면 run에서는 그렇게 할 수 없습니다.

대신 `run -env=windows.env,site.env` 처럼 실행할때 os별로 다른 env를 설정하도록 할 수 있습니다.

windows.env 의 예
```
SITE_ROOT=//example
```

linux.env 의 예
```
SITE_ROOT=/example
```

**Comment by 78963l** [comment]
> 혹시 리눅스와 윈도우즈 환경변수를 한번에 잡으시려는 거라면 run에서는 그렇게 할 수 없습니다.
> 
> 대신 `run -env=windows.env,site.env` 처럼 실행할때 os별로 다른 env를 설정하도록 할 수 있습니다.
> 
> windows.env 의 예
> 
> ```
> SITE_ROOT=//example
> ```
> 
> linux.env 의 예
> 
> ```
> SITE_ROOT=/example
> ```

아하 리눅스와 윈도우즈 환경변수를 한번에 잡으려고 했었어요, 그렇군요 답변 감사합니다!

**Comment by kybin** [comment]
네, 이 이슈는 닫을게요. 혹시 또 궁금하신것 있으시면 이슈 남겨주세요~
