### ISSUE TITLE
Os가 linux인지 window인지 어디서 판별하고 어느 변수에담기는지 궁금합니다..

### ISSUE THREAD

**Issue by 78963l** [studio2l/run#6]

**Comment by kybin** [comment]
현재는 그런 기능이 없습니다. 저희는 컴퓨터마다 기본 환경변수를 따로 잡기 때문인데요. 필요하시면 만들어 드릴수 있습니다. RUN_OS라고 만들 계획이 이미 있어요~

**Comment by 78963l** [comment]
아하 그건 제가 한번만들어볼께요! 답변 감사합니다.

**Comment by kybin** [comment]
오 좋죠! ㅎㅎㅎ
